### PR TITLE
unstaged product of beta version 

### PR DESCRIPTION
**Pull request by tichimura-pivotal**
the task.sh script is not capable for handling "x.x.x-beta" kinds of product version.
It will fail when jq try to check the product name and version is matched with what we had been uploaded.
It should return "1" as a result of finding the version from the unstaged products.

https://github.com/tichimura-pivotal/pcf-pipelines/blob/192b18ee49cb3f9daf3eab32506042846114e441/tasks/stage-product/task.sh#L51

* Expected result after the change:

pass the `if [ "$(echo $UNSTAGED_PRODUCT | jq '. | length')" -ne "1" ] `

* Current result before the change:

returns 0 from `if [ "$(echo $UNSTAGED_PRODUCT | jq '. | length')" -ne "1" ]`

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `master` branch

* [x] I have run all the unit tests

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tichimura-pivotal Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=304)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=304) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tichimura-pivotal Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=304)!

**Comment by abbyachau** [comment]
@tichimura-pivotal were you able to reset the pipeline based on our discussion (i.e. use the product version in PivNet and remove the regex). Thanks.

**Comment by abbyachau** [comment]
Hi @tichimura-pivotal, as discussed - please let me know if we can close this pull request. It sounds as though you are working through deploying a 2.1 release candidate. Your pull request also includes other changes which you've not detailed. Thanks.

**Comment by abbyachau** [comment]
Hi @tichimura-pivotal closing this issue due to inactivity, please do not hesitate to reach out if you have further questions/feedback.

**Pull request closed without merging**
