### PR TITLE
Support folder for OpsMan ova import

### PR DESCRIPTION
**Pull request by camattin**
Possibly a better way to do this, but we must deploy the ops manager VM into a folder; these changes make that functional by defining OM_VM_FOLDER in your secrets. I'd love to not have to maintain my fork just for this simple change. :-)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@camattin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=180) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@camattin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=180)!

**Comment by abbyachau** [comment]
Hi @camattin thanks - please can you let us know why the Ops Man vm in your case must be deployed in a folder? Thank you.

**Comment by camattin** [comment]
Organizational reasons. We will have more than one foundation deployed per vCenter, so it will be ideal to have each customer's OM VM inside its own folder.

**Comment by krishicks** [comment]
Management of the location of resources in vSphere is up to the customer, so allowing deploying of the OpsMgr VM into a folder is reasonable to me.

**Comment by abbyachau** [comment]
Hey thanks both @camattin and @krishicks - this story has already been scheduled.

**Comment by christianang** [comment]
Hi @camattin,

Sorry for the delay on this PR. It looks good to me, but it is currently in a conflicting state. Could you resolve any conflicts with master and we will pull it in.

Thanks,
Christian

**Comment by camattin** [comment]
Hi Christian, I believe I have the conflicts resolved.

**Comment by christianang** [comment]
Looks like we still can't squash and merge this properly. Rebasing these nine commits are still giving us conflicts. Can you squash all the commits into a single commit that is rebased onto our master?

**Comment by camattin** [comment]
This page is now showing me "This branch has no conflicts with the base branch" and when I start another PR on my repo, it's showing that they are able to be merged. If there's something else I need to do on my end, let me know. (I'm happy to blow away my repo and simply re-do the changes from the start if needed. :-) )

**Comment by christianang** [comment]
Looks like I can merge it now. Not sure what was going on. Thanks for the PR and sorry for the back and forth! 💯

**Pull request merged**
