### PR TITLE
terrafrom state config able to use other regions for S3

### PR DESCRIPTION
**Pull request by clijockey**
At the moment the AWS install pipeline terrafrom resource falls back to the default region of US-EAST-1 however it is required to make use of other regions as part of customer installs in EMEA. As a result the `region_name: {{TF_VAR_aws_region}}` value has been added to override default behavior.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@clijockey Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=216)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=216) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@clijockey Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=216)!

**Comment by abbyachau** [comment]
Hi @clijockey, thanks for raising this issue. We've actually just merged in a duplicate pr: https://github.com/pivotal-cf/pcf-pipelines/pull/214. This fix will be part of v20, which we plan to release soon. Please let us know if you have any questions.

**Comment by clijockey** [comment]
@abbyachau, I missed that one somehow on my searching. I will be doing a new PR once I have worked out the testing process to enhance this further to allow the installation of PCF itself into other regions (currently hardcoded for US-EAST-1). What sort of timeline are you looking at for v20 release?

**Comment by clijockey** [comment]
@abbyachau Done PR #217 to add the additional multi-region functionality to support EMEA regions (and newer regions).

**Pull request closed without merging**
