### PR TITLE
Added auth using client id/secret

### PR DESCRIPTION
**Pull request by mevansam**
Modified pipeline and task scripts to accept additional credential environment variables and provide and alternate authentication capability when ops manager has been set up with SSO.

### CODE REVIEW

**Comment by abbyachau** [comment]
Hey @mevansam, many thanks for sending through this PR. Apologies for the delay in response. Could you please expand further on what solutions/enhancements this PR provides us with? Thanks again.

**Comment by mevansam** [comment]
Hi @abbyachau. This to enable using client id and client secret as an alternative authentication capability for `om` when Ops Manager is configured with SSO.

**Comment by krishicks** [comment]
I wanted to get out in front of this before too much time went on so I looked at what it would take to pull this in, and it's a bit more work than is done in this PR. I've created a WIP branch, [add-sso-login(https://github.com/pivotal-cf/pcf-pipelines/tree/add-sso-login), which contains all the changes to support this across all uses of `om-linux`. It hasn't been tested, so it may be incomplete, and I think we should test each pipeline individually before deciding it's OK to pull in as so many files are changed.

**Comment by mevansam** [comment]
Hi @krishicks thanks. I am good with working with the WIP branch. Perhaps SSO could be handled more elegantly, as it seemed very cumbersome to implement it the way I did.

**Comment by sbayyapureddy** [comment]
Is there a reason for not merging these changes in Main? We are switching to SSO but current pipelines  don't support SSO. Please let me know

**Comment by abbyachau** [comment]
Hi @sbayyapureddy, thanks, we'll get back to this pr very soon - it's on our radar. Thanks for your patience.

**Comment by krishicks** [comment]
The reasons for this not being merged in are in my above comment, which was acknowledged by @mevansam.

**Comment by abbyachau** [comment]
Hi @mevansam and @sbayyapureddy, because the codebase has diverged since @mevansam's original PR, we've created a new story for this work: https://www.pivotaltracker.com/story/show/153187892, which we've prioritised. Thanks.

**Comment by abbyachau** [comment]
Hi @mevansam and @sbayyapureddy we've added this functionality in [v22](https://github.com/pivotal-cf/pcf-pipelines/releases/tag/v0.22.0). Please let us know if you have any feedback by creating a new issue. Thanks!

**Pull request closed without merging**
