### PR TITLE
Gov cloud support

### PR DESCRIPTION
**Pull request by rotaryczar**
Thanks for contributing to pcf-pipelines. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
Due to the fact gov cloud does not have route53. We have modified the pipeline to support a commercial AWS route 53 by using two providers conditionally 

* An explanation of the use cases your change solves:
Gov cloud not having route53

* Expected result after the change:
Backward compatibility but allows gov cloud to deploy along side with commercial AWS route53 

* Current result before the change:
PCF pipelines fail with gov cloud due to gov cloud not having route53

* Links to any other associated PRs or issues:

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `master` branch

* [x] I have run all the unit tests

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rotaryczar Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=313)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=313) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rotaryczar Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=313)!

**Comment by abbyachau** [comment]
Hi @rotaryczar @sneal thanks for creating this. We have a story in the backlog to support external DNS, where as an additional task, we will be reviewing your pull request. Here is the tracker story: https://www.pivotaltracker.com/story/show/152422355 for reference. Thanks again.

**Comment by calebwashburn** [comment]
Thanks for the pull request.  We are going to be revisiting the approach for how to user pipelines to run a more flexible iaas paving.  We will keep these requirements in play as we look forward to the new direction.

**Pull request closed without merging**
