### PR TITLE
All VMs in ERT when using install-pcf are configured as internet connected

### PR DESCRIPTION
**Pull request by srbry**
### What?

When running the install-pcf pipelines the resource config for all vms is set as `"internet_connected": true`, currently there is no way of overriding this outside of the ops manager GUI.

This is in contradiction to the install docs: https://docs.pivotal.io/pivotalcf/1-12/customizing/azure-er-config.html#resources.
`Ensure that the Internet Connected checkboxes are deselected for all jobs.`

This PR proposes adding a global param of `internet_connected` so you can choose if you would like to have internet connected resources or not. At the moment this is a global option (for all resources), a future enhancement might be to allow this setting on a per resource basis.

### How to review?

In order to test this functionality you may want to perform some yaml patching. The approach I have taken is to add an additional resource to my `pipeline.yml` and use it with the `configure-ert` job. If you would also like to set the value for `true` using the a `params.yml` file then you need to edit your `pipeline.yml` to include the correct param on your task. The yaml patch command and file I used:
```
---
- op: add
  path: /resources/-
  value:
    name: pcf-pipelines-forked
    type: git
    source:
      uri: git@github.com:A-CMS/pcf-pipelines.git
      branch: master
      private_key: {{git_private_key}}

- op: replace
  path: /jobs/name=configure-ert/plan/0/aggregate/get=pcf-pipelines
  value:
    get: pcf-pipelines
    resource: pcf-pipelines-forked

- op: add
  path: /jobs/name=configure-ert/plan/task=configure-ert/params/INTERNET_CONNECTED
  value: {{internet_connected}}

- op: add
  path: /jobs/name=configure-ert/plan/task=configure-ert/params/IAAS
  value: azure
```
```
sed -e "s/{{/'{{/g" -e "s/}}/}}'/g" install-pcf/azure/pipeline.yml | yaml-patch -o patch.yml |  sed -e "s/'{{/{{/g" -e "s/}}'/}}/g" > patched-pipeline.yml
```

### CODE REVIEW

**Comment by srbry** [comment]
Having looked at this in some extra detail it looks like we have two task directories.
  1. `config-ert` which is used by Azure, Openstack and vSphere
  1. `configure-ert` which is used by aws and gcp.

Is there a good reason for this or should we also be cleaning this up for clarity? I don't expect this change to cause any problems by Openstack or vSphere but it looks like the functionality I am adding is mostly already there for aws and gcp, with the exception that it is set to `false` by default with no way of overriding.

**Comment by abbyachau** [comment]
Hi @srbry, thank you for creating this pull request. Our team reviewed your pull request and have advised that unfortunately pulling in the changes will have adverse effects on the vSphere pipeline. We've created a separate story based on your feedback here to review the aforementioned task: https://www.pivotaltracker.com/story/show/152083079. 

Please let us know if you have a workaround? It is not ideal, but you could fork the pipelines if your work is time sensitive. Thanks, and speak soon.

**Comment by srbry** [comment]
Hi @abbyachau thanks for the feedback. I have added a new commit with a slightly nasty workaround. It will only alter the `cf_resources` if the `IAAS` is set to azure (set by the pcf-install azure pipeline). I am sure there is a more elegant way of doing this. I also think longer term we should only have one script for `config-ert` having both a `config-ert` and `configure-ert` that seem to be doing almost identical functions is quite confusing.

**Comment by abbyachau** [comment]
Hi @srbry, thanks for this. Until we've looked into either consolidating the two config ERT files, or implementing a fix for `internet_connected`, it might be best for you to fork our repo. Please let us know if that would be a problem, thanks.

**Comment by srbry** [comment]
For now we are running by just forking this task and yaml patching our pipeline as described in the above description. I'm fairly confident the current version of this PR would not impact other pipelines so could be considered a fix for `internet_connected` with Azure. If you would like me to look at a different approach I am happy to amend or re-raise this PR

**Comment by abbyachau** [comment]
Hi @srbry, thanks again for raising this issue. We've added a new configurable param `internet_connected:` for each of the IAASs. Please let us know if you have any feedback or questions. Thanks for your patience on this one.

**Comment by krishicks** [comment]
Why should this be configurable at all?

```
Ensure that the Internet Connected checkboxes are deselected for all jobs.
```

There is no reason for the jobs to be internet-connected; if they are it is a mistake that should be rectified, not parameterized.

**Comment by eamonryan** [comment]
@krishicks I just did some checking and found that for the public IaaSes (where this checkbox is actually present) the recommendation for this checkbox has changed between PCF 1.11 and PCF 1.12. In 1.12 we now provide steps for the creation of a NAT box on each public IaaS and internet connected should be deselected. In 1.11 there were no NAT box steps so `Connected` was recommended.

Reference for PCF 1.11:
https://docs.pivotal.io/pivotalcf/1-11/customizing/gcp-er-config.html#config-lb
```
Verify that the Internet Connected checkbox for every job is checked to allow the jobs to reach the Internet. This gives all VMs a public IP address that enables outbound Internet access.
```

PCF 1.12:
https://docs.pivotal.io/pivotalcf/1-12/customizing/gcp-prepare-env.html#create_nat
https://docs.pivotal.io/pivotalcf/1-12/customizing/gcp-er-config.html#config-lb
```
Verify that the Internet Connected checkbox for every job is unchecked. When preparing your GCP environment, you provisioned a Network Address Translation (NAT) box to provide Internet connectivity to your VMs instead of providing them with public IP addresses to allow the jobs to reach the Internet.
```

The `create_nat` step is not present in the PCF 1.11 docs.

**Comment by krishicks** [comment]
That information is interesting because the GCP install-pcf pipeline hasn't changed at all in that time; it's been `internet_connected: false` for all the jobs since it was merged in to pcf-pipelines in 5339b05.

**Comment by abbyachau** [comment]
Hi @srbry we are closing this pull request because we've implemented a fix -  please use [v19.2]( https://github.com/pivotal-cf/pcf-pipelines/releases) which includes this new param `internet_connected`. Please do not hesitate to get in touch if you have any questions/feedback.

**Pull request closed without merging**
