### PR TITLE
Updated help in params.yml & errands in bootstrap

### PR DESCRIPTION
**Pull request by ollema**
Updated the help text/comments in params.yml for the
parameter that determines which errands to run, to reflect
the actual errand names used in PAS 2.0.

Also fixed what errands to disable in bootstrap.sh, so that this
also uses the correct errand names.

Fixes: https://github.com/pivotal-cf/pcf-pipelines/issues/286

### CODE REVIEW

**Comment by abbyachau** [comment]
Original issue: https://github.com/pivotal-cf/pcf-pipelines/issues

**Comment by pivotal-issuemaster** [comment]
@ollema Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=287)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=287) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ollema Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=287)!

**Comment by ollema** [comment]
not sure why this is failing the check?

**Comment by abbyachau** [comment]
@ollema just double checking you have signed the CLA?

**Comment by ollema** [comment]
@abbyachau yeah, I did change my GitHub handle since then, maybe that's why it's not registering? when I follow the links to sign the CLA it already says that I've signed it though..

**Comment by ollema** [comment]
screenshot_20180305-092858 2

**Comment by abbyachau** [comment]
@ollema  I checked with our Legal team, and there's a CLA check issue when change your GitHub account. They have a story in their backlog to fix this issue. This pull request's been scheduled for engineering review. Thanks.

**Pull request merged**
