### PR TITLE
Externalizing the disk configuration for OM as default is 30 GB and n…

### PR DESCRIPTION
**Pull request by rahulkj**
Externalizing the disk configuration for OM as default is 30 GB and now from params you can specify the OM disk size. We were running into issues with upgrades, where the disk was full on OM

Thanks to @dwntwnbrown

### CODE REVIEW

**Comment by rahulkj** [comment]
had missed adding the `om_disk_size_in_gb` to the `variables.tf` files

**Comment by rahulkj** [comment]
Fixing the IAAS_TYPE for azure stemcell download, it was set to `aws`

**Comment by pivotal-issuemaster** [comment]
@rahulkj Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=187) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by abbyachau** [comment]
hey @rahulkj we've just linked the CLA agreement to pcf-pipelines repo - however, I don't know why it is asking you to sign it. Please ignore and I'll look into it. Thanks.

**Comment by pivotal-issuemaster** [comment]
@rahulkj Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=187)!

**Comment by rahulkj** [comment]
@abbyachau - resolved the CLA checks..

**Comment by christianang** [comment]
Hi @rahulkj,

Sorry for the delay in looking at this. It looks like there are some conflicts. Would you mind fixing them before we pull your changes in. Other than that it looks good and will pull it in as soon as the conflicts are resolved.

**Comment by rahulkj** [comment]
Updated

**Comment by christianang** [comment]
Thanks

**Pull request merged**
