### PR TITLE
Add nfsbrokerpush job to GCP ERT configuration

### PR DESCRIPTION
**Pull request by bijukunjummen**
[#146020615]

### CODE REVIEW

**Comment by krishicks** [comment]
What about the JSON changes for the passwords that were put in the AWS one?

https://github.com/pivotal-cf/pcf-pipelines/commit/12be12c02d5f47f46b53acad18260cb9bc70dbfa

**Comment by bijukunjummen** [comment]
Those are there in the gcp params and the tasks as part of the previous PR, let me quickly double check.

**Comment by bijukunjummen** [comment]
Both AWS and GCP goes through the same `configure-json` flow except for the base template, this job configuration was missed from the GCP one.

**Comment by krishicks** [comment]
Ah, I see. I should have kept scrolling the diff.

**Pull request merged**
