### PR TITLE
Update task.sh

### PR DESCRIPTION
**Pull request by Klojo**
change govc device.disconnect -vm.ipath=${opsman_path} in govc device.disconnect -vm.ipath=${OPSMAN_PATH}

Thanks for contributing to pcf-pipelines. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

* An explanation of the use cases your change solves:

* Expected result after the change:

* Current result before the change:

* Links to any other associated PRs or issues:

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `master` branch

* [x] I have run all the unit tests

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Klojo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=280)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=280) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Klojo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=280)!

**Comment by abbyachau** [comment]
@Klojo thanks apologies for the delay in response. Prioritising for engineer review.

**Comment by abbyachau** [comment]
Hi @Klojo thanks again for this. As discussed, we've updated/enhanced this task recently and therefore will not be pulling in your pull request. Thank you anyway.

**Pull request closed without merging**
