### PR TITLE
Changed instance type for opsman from m3.large to m4.large

### PR DESCRIPTION
**Pull request by cxhercules**
This is to address issue with instance type, closes https://github.com/pivotal-cf/pcf-pipelines/issues/193

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cxhercules Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=194) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by abbyachau** [comment]
Hi @cxhercules, thanks for creating this pull request. We've not seen issues with using `m3.large` with `us-east-1a` - are you still seeing this issue? Thanks.

**Comment by abbyachau** [comment]
Hi @cxhercules we plan to close this pull request due to inactivity. If you are still experiencing the issues you described [here](https://github.com/pivotal-cf/pcf-pipelines/issues/193), please let us know. Thanks.

**Comment by abbyachau** [comment]
Thanks @cxhercules, closing this issue, as discussed.

**Pull request closed without merging**
