### PR TITLE
add initial install for isolation segment and windows runtime

### PR DESCRIPTION
**Pull request by wjk940**
this pull adds new files and directories to implement pipelines for initial install of two tiles: isolation segment, windows runtime

### CODE REVIEW

**Comment by wjk940** [comment]
updating PR to include Redis and APM - both tested on vsphere - all of the backup options for Redis need testing - I tried No Backups and S3 Backups.

**Comment by abbyachau** [comment]
Hi @wjk940, thanks for this pr. You may of had a response via a different channel about this pr - sorry a response has taken so long via this channel. We do not currently have plans to introduce new pipelines functionality for installing specific tiles but it is on our radar as a useful feature. We do have a pipeline (upgrade-tile), which upgrade tiles that are already installed on Ops Manager - this is supported only for patch release (as patch release typically do not introduce config changes). We'll keep this pr open in case we do decide to introduce installing specific tiles (in particular isolation segments, which is near the top of our list if we do introduce this functionality.) However, given how much refactoring we've done to pcf-pipelines since April, we may likely want to look into implementing our own solution. Please do not hesitate to get in touch if you have any questions, or feedback. Thanks again.

**Comment by pivotal-issuemaster** [comment]
@wjk940 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=12) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by abbyachau** [comment]
Hi @wjk940, we are closing this pr due to age. Our codebase has diverged significantly since April. If we do plan on implementing this feature, we can use your pull request as reference. Sorry about that - please let us know if you have any feedback. Thanks.

**Pull request closed without merging**
