### PR TITLE
Add more chars into ENV_SHORT_NAME

### PR DESCRIPTION
**Pull request by kamoljan**
Keep ENV_SHORT_NAME unique account names across resource groups

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kamoljan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=236)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=236) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kamoljan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcf-pipelines&pullRequestId=236)!

**Comment by abbyachau** [comment]
HI @kamoljan thanks for this. Could you please provide a description of what this pull request is meant to achieve. Thanks again.

**Comment by kamoljan** [comment]
@abbyachau added a description in the following PR https://github.com/pivotal-cf/pcf-pipelines/pull/245

**Pull request closed without merging**
