### PR TITLE
Allow user to apply optional tags to managed resources

### PR DESCRIPTION
**Pull request by jgeorge300**
Thanks for contributing to pcf-pipelines. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
Allow the user to specify additional tags to be applied managed resources.

* An explanation of the use cases your change solves:
AWS tags are used to tie related resources together to make them easy to identify. 

* Expected result after the change:
Created resources will be tagged with the same set of common tags.

* Current result before the change:
Resources are only tagged with a name

* Links to any other associated PRs or issues:

* [* ] I have viewed signed and have submitted the Contributor License Agreement

* [ *] I have made this pull request to the `master` branch

* [ *] I have run all the unit tests

### CODE REVIEW

**Comment by abbyachau** [comment]
Thanks, @jgeorge300. Prioritising for engineering work.

**Comment by abbyachau** [comment]
Hi @jgeorge300, thanks again for creating this pr. Can you tell us what your use case is and why searching by `terraform_prefix` (a searchable term to group resources) does not fulfill your use case?

**Comment by jgeorge300** [comment]
The `terraform_prefix` tag will only be on the resources created by this project. We have additional tags that we require on all taggable resources. i.e. `InTerraform=true` or `InTerraform=false`, billing codes, etc ...

**Comment by calebwashburn** [comment]
Thanks for PR but closing as we are looking to have more configurable approach to allow you to configure your iaas in the future.

**Pull request closed without merging**
